周一:
  启用: false
  name: 二楼东  # 二楼东/二楼西/四楼/三楼大厅/守正书院/求新书院/自定义
  开始时间: 0
  持续小时数: 0
周二:
  启用: false
  name: 二楼东
  开始时间: 0
  持续小时数: 0
周三:
  启用: false
  name: 二楼东
  开始时间: 0
  持续小时数: 0
周四:
  启用: false
  name: 二楼东
  开始时间: 0
  持续小时数: 0
周五:
  启用: true
  name: 二楼西
  开始时间: 8
  持续小时数: 13
周六:
  启用: true
  name: 二楼西
  开始时间: 8
  持续小时数: 13
周日:
  启用: false
  name: 二楼东
  开始时间: 0
  持续小时数: 0

自定义:
    - 10000
    - 10001

# 3东：42101-42140
# 3西：42141-42184
# 3北: 42185-42215
# 5： 43285-43455 （包括但不仅限于，json包懒得看，以下同理（（（（）
# 7： 42587-42700
# 8： 42710-42842
# 9： 42887-42978
# 10：43031-43114
# 11：43153-43266

